version: '3.7'

services:
  ms-storage-app:
    container_name: ms-storage-app
    image: ms-storage
    ports:
      - "8083:8083"
    networks:
      - microservices_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ms-song-app:
    container_name: ms-song-app
    image: ms-song
    ports:
      - "8082:8082"
    networks:
      - microservices_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ms-resource-processor-app:
    container_name: ms-resource-processor-app
    image: ms-resource-processor
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - rabbit_network
      - microservices_network
    depends_on:
      - rabbit
      - ms-song-app

  ms-resource-app:
    container_name: ms-resource-app
    image: ms-resource
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - rabbit
      - ms-resource-processor-app
      - ms-song-app
    networks:
      - rabbit_network
      - microservices_network
      - localstack_network

  eureka-server-app:
    container_name: eureka-server
    image: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices_network

  api-gateway-app:
    container_name: api-gateway
    image: api-gateway
    restart: always
    ports:
      - "8090:8090"
    networks:
      - microservices_network
    depends_on:
      - eureka-server-app

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '127.0.0.1:4566:4566'
    networks:
      - localstack_network
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh

  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbit_network

networks:
  rabbit_network:
    external: true
  microservices_network:
    external: true
  localstack_network:
    external: true
