spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: resource-service

aws:
  region: us-east-1
  access-key: test
  secret-key: test
  bucket-name: resource-bucket
  s3.endpoint: http://localstack:4566

queue:
  processing-queue: PROCESSING_QUEUE
  success-queue: SUCCESS_QUEUE

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

feign:
  retryAttempts: 5
  retryPeriod: 2000

service:
  storage.endpoint: http://api-gateway:8090/storage-service