spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/testDB
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

aws:
  region: us-east-1
  access-key: test
  secret-key: test
  bucket-name: resource-bucket
  s3.endpoint: http://127.0.0.1:4566

queue:
  processing-queue: PROCESSING_QUEUE